version: '3.8'

services:
    mosquitto:
        image: eclipse-mosquitto:2.0.14
        container_name: mosquitto
        ports:
            - "1883:1883"
        volumes:
            - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./mosquitto/data/mosquitto_passwd.conf:/mosquitto/data/mosquitto_passwd.conf
            # - ./mosquitto/log/mosquitto.log:/mosquitto/log/mosquitto.log

    filebeat:
        image: docker.elastic.co/beats/filebeat:7.10.2
        container_name: filebeat
        depends_on:
            - mosquitto
        entrypoint: "filebeat -e -strict.perms=false"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
